### ISSUE TITLE
Parsing gives garbage results for large hex strings

### ISSUE THREAD

**Issue by Storyyeller** [peterolson/BigInteger.js#101]
The documentation says that if a string and base are provided, then it will parse the string in that base and throw an error if parsing fails. However, this is not the actual behavior.

For example, it will silently accept a "0x" prefix. The worst part is that this appears to work for small numbers, but produces garbage results for large numbers, with absolutely no indication of an error.

```
> bigInt("0x10000", 16)
{ [Number: 65536] value: 65536, sign: false, isSmall: true }
> bigInt("0x100000000", 16)
{ [Number: 4294967296] value: 4294967296, sign: false, isSmall: true }
> bigInt("0x1000000000000", 16)
{ [Number: 148900262679937020] value: [ 9937024, 26267, 1489 ], sign: false, isSmall: false }
> bigInt("1000000000000", 16)
{ [Number: 281474976710656] value: 281474976710656, sign: false, isSmall: true }
> 

```

**Comment by benjaminBrownlee** [comment]
Just to make sure I'm understanding you correctly, is the problem the fact that improper syntax (for example, using the "0x" prefix) does not throw back an error but rather useless numbers?

**Comment by Storyyeller** [comment]
Yes. The ideal situation would be that it throws an error as per the documentation, but if it didn't, it would be better to at least behave consistently instead of sometimes working and sometimes producing garbage results. This caused a bug that took me a while to track down.

**Comment by peterolson** [comment]
This is a good point to raise, this definitely should be fixed. I'll try to look at it soon. 

I haven't investigated carefully yet, but the reason behind the discrepancy in behavior is probably due to using the native JavaScript toString method for base conversion for small numbers in base 2-36.

The reason for the garbage results is that x is interpreted as a digit for 33. That is, x0 in base 10 will be interpreted as 330. Ideally we shouldn't allow digits that are larger than the base.

**Comment by peterolson** [comment]
This should be fixed now, let me know if you have any more issues. Thanks!
