### ISSUE TITLE
TypeScript file instead of Definition files?

### ISSUE THREAD

**Issue by courteous** [peterolson/BigInteger.js#115]
One simple question, can you please make the typescript file available instead of a definition. Is there any plans on that?

**Comment by peterolson** [comment]
The library is written in plain JavaScript. I don't see a compelling reason to port it to TypeScript, since it might be an obstacle to some people who would like to contribute.

Having a definition file seems to be a decent solution for those wanting to use BigInteger in TypeScript. Are you having any issues using the definition file?

**Comment by courteous** [comment]
peterolson, first many thanks for the reply and for your work on this library. I am intending to port the library to typescript, simply because  of a reason that when types are presented the code looks much cleaner and it is easier to spot things that have not been seen before (but this is strictly my opinion). I would present the ported version soon. I would love if you take a look over the types since it is really crucial to get those right.
