### ISSUE TITLE
Convert Numbers to words representation

### ISSUE THREAD

**Issue by P9Q** [peterolson/BigInteger.js#133]
It would great if you add this method like:
[Number To Words Converter](https://www.calculatorsoup.com/calculators/conversions/numberstowords.php)
[Names of large numbers](http://en.wikipedia.org/wiki/Names_of_large_numbers)

var words = bigInt("75643564363473453456342378564387956906736546456235345").toWords() => seventy-five sexdecillion, six hundred forty-three quindecillion, five hundred sixty-four quattuordecillion, three hundred sixty-three tredecillion, four hundred seventy-three duodecillion, four hundred fifty-three undecillion, four hundred fifty-six decillion, three hundred forty-two nonillion, three hundred seventy-eight octillion, five hundred sixty-four septillion, three hundred eighty-seven sextillion, nine hundred fifty-six quintillion, nine hundred six quadrillion, seven hundred thirty-six trillion, five hundred forty-six billion, four hundred fifty-six million, two hundred thirty-five thousand, three hundred forty-five

**Comment by username1565** [comment]
You can using this:
https://ourcodeworld.com/articles/read/353/how-to-convert-numbers-to-words-number-spelling-in-javascript (see paragraph "B. Self implementation")
This working with strings. And function from here can be called by code, like this:
```javascript
console.log(numberToEnglish(YOUR_bigInt.toString()));
```
scales you can see here: http://users.skynet.be/nizgorur/very_big_numbers.htm
But wait...

...And I writed full array, here: https://codepen.io/anon/pen/MGPZmE
You can see big string_number, then words in the bottom on this page.

There is a modified function with array (exponents from 3 to 3003, step 3),
there is big number-string generator (value up to 10^3003),
regular expression for split big-number-string, and...
running this with custom delimiters:
```javascript
document.write(numberToEnglish(number, 'hehheh', '_', '; '));
```

All code is in JTML and no need to include anything. This is copyable and working locally in HTML-file.
Have a nice day.

**Comment by username1565** [comment]
You can using this:
https://ourcodeworld.com/articles/read/353/how-to-convert-numbers-to-words-number-spelling-in-javascript (see paragraph "B. Self implementation")
This working with strings. And function from here can be called by code, like this:
```javascript
console.log(numberToEnglish(YOUR_bigInt.toString()));
```

"scales", you can see here: http://users.skynet.be/nizgorur/very_big_numbers.htm
But wait...
...and I already writed full array for scales - here: https://codepen.io/anon/pen/MGPZmE
You can see BIG STRING NUMBER, and then words - in the bottom of those page.

There is a modified function, with FULL SCALES-ARRAY (exponents of base 10 - from 3 to 3003, step 3),
also, there is big-number-string-generator (value up to 10*10^3003),
regular expression for split big-number-string by 90 rows and 3 digits for each,
and running this with custom delimiters:
```javascript
document.write(numberToEnglish(number, 'hehheh', '_', '; '));
```
All code is in HTML, there and no need to include anything.
This is copyable and working locally in HTML-file.

Also, you can put this in JS, without tag
```HTML
<script>
</script>
```
then save this in JS-file near your BigInteger.js,
comment functions, and include code then, like this bigInt-library.

Have a nice day.

P.S.: Hm... I still don't know how to add hyphen for get seventy-five.

**Comment by peterolson** [comment]
This is a good idea, but I think it would be better to put this in a separate library as a plug-in to this one. I want to avoid bloating this library with lots of features, and parsing and outputting words is a fairly complicated feature.

**Comment by P9Q** [comment]
I myself wrote this feature in just 19 lines of codes(including arrays of the words), I just felt that this feature might be useful for the package, anyway thanks for the replies.

**Comment by username1565** [comment]
hyphen added there: https://codepen.io/anon/pen/MGPZmE

**Comment by username1565** [comment]
Also, first nulls are deleted from string, if this is exists there.

**Comment by P9Q** [comment]
@username1565, It would be great if you complete the code and add support for float numbers like this [website](https://www.calculatorsoup.com/calculators/conversions/numberstowords.php) for example:
 `1.5555555555555555` 
will be:
`one and five quadrillion, five hundred fifty-five trillion, five hundred fifty-five billion, five hundred fifty-five million, five hundred fifty-five thousand, five hundred fifty-five ten-quadrillionths`

complete the code and put it as a package on github let others enjoy your package! 👍

**Comment by username1565** [comment]
@P9Q Oww, wow... Where you can see quadrillion, there?
Not very good example, because so many digits have value five - in the number.

How need to dysplay, for example, the value of:
92156000.1565218953159600000001001013? 
I see suffix-th's for scales on https://translate.google.com/
for example: one whole and five tenths, eight ten thousandths,
nine hundred thousandth hundred millionths.

Also, you didn't write delimiter after 1, I mean float point.
This can be a word "point" or some another?..

I cann't open your website, because I see an error:
403: Forbidden
You don't have permission to access /calculators/conversions/numberstowords.php on this server.
Maybe this regional limits... So I did open by using https://hide.me/
and I see float numbers not translated correctly to the words...

Yeap, I can upload this here to github. But at first, I want to do complete this and wait your propositions.
Best regards.

**Comment by username1565** [comment]
@P9Q, look again at my previous example on the site CodePen.io :P
There is your example, with end delimiter.

**Comment by username1565** [comment]
@P9Q, look again at my previous code on the site CodePen.io :P
There is your example with number 1.5555555555555555 , and with and whole-delimiter.
I did wrote float number generator there as separate function, and fix previous bugs.
For example, chunk delimiter was been added if (number-lenght % 3==0)
You can see the comments in the code.

I don't know how to upload this to github, you can do this yourself. Have a nice day.

**Comment by username1565** [comment]
Your example 92156000.1569795899999999999999999999999999999999999
give me the answer: 
Ninety-two million, then one hundred and fifty-six thousand, then whole, and one tredecillion, five hundred and sixty-nine duodecillion, seven hundred and ninety-five undecillion, eight hundred and ninety-nine decillion, nine hundred and ninety-nine nonillion, nine hundred and ninety-nine octillion, nine hundred and ninety-nine septillion, nine hundred and ninety-nine sextillion, nine hundred and ninety-nine quintillion, nine hundred and ninety-nine quadrillion, nine hundred and ninety-nine trillion, nine hundred and ninety-nine billion, nine hundred and ninety-nine million, nine hundred and ninety-nine thousand, nine hundred and ninety-nine ten-tredecillionths.

because there is a nulls in the end of whole part.

So this is fixed
```javascript
if(i!==chunksLen-1 && chunks[i+1]!=='-' && chunks[i]!=='000'){words.push(chunk_delimiter);}
```
See again:

**Comment by username1565** [comment]
Your example 92156000.1569795899999999999999999999999999999999999
give me the answer:
Ninety-two million, then one hundred and fifty-six thousand, then whole, and one tredecillion, five hundred and sixty-nine duodecillion, seven hundred and ninety-five undecillion, eight hundred and ninety-nine decillion, nine hundred and ninety-nine nonillion, nine hundred and ninety-nine octillion, nine hundred and ninety-nine septillion, nine hundred and ninety-nine sextillion, nine hundred and ninety-nine quintillion, nine hundred and ninety-nine quadrillion, nine hundred and ninety-nine trillion, nine hundred and ninety-nine billion, nine hundred and ninety-nine million, nine hundred and ninety-nine thousand, nine hundred and ninety-nine ten-tredecillionths.

words ', then whole, and', because there was been a nulls - in the end of whole part.

Also, the number 9215600000000000000000000000000000000000000000000000
give me an answer, like: Nine sexdecillion, then two hundred and fifteen quindecillion, then six hundred quattuordecillion, then , then , then , then , then , then , then , then , then , then , then , then , then , then , then .

So this is fixed by code:
```javascript
if(i!==chunksLen-1 && chunks[i+1]!=='-' && chunks[i]!=='000'){words.push(chunk_delimiter);}
```
See that's all again, there.

**Comment by username1565** [comment]
Now, you can also see this code here: https://github.com/username1565/numbers_to_words

**Comment by P9Q** [comment]
@username1565, I will help you with extending this project, maybe support for other languages etc :)

**Comment by username1565** [comment]
To do this multilangual, can be expediently using separate files for each language.
But this need to write big arrays for scales in each HTML-file.
Will be better to use more elegand law to do working with prefixes, and suffixes of names for digits.
Then this all can be extend by using LONG SCALE.
I think the code can be writed compactly, if laws will be extracted from OS dll-s or another library.
More operation systems supporting multilangual translating, and this all already exists there.

**Comment by username1565** [comment]
Also, I did cloning PeterOlson's BigInteger, and modify the main BigInteger.js.
You can see changes here:
https://github.com/username1565/BigInteger/commit/646a809f8da85819c4b986149224057f055f88f3

**Comment by username1565** [comment]
@P9Q

To do this multilangual, can be expediently using separate files for each language.
But this need to write big arrays for scales in each HTML-file.
Will be better to use more elegand law to do working with prefixes, and suffixes of names for digits.
Then this all can be extend by using LONG SCALE.
I think the code can be writed compactly, if laws will be extracted from OS dll-s or another library.
More operation systems supporting multilangual translating, and this all already exists there.

Also, I did cloning PeterOlson's BigInteger, and modify the main BigInteger.js.
You can see changes here:
https://github.com/username1565/BigInteger/commit/5bfea9f1f2db6dbd2933558dd26ab59e91a2921a

Now I working with UniCode symbols to make convertation BigInteger to Unicode String, and got BigInteger from this string.
This need to contains Unicode Alphabet with copyable symbols, without any special symbols,
and then the base (radix) can be greater and larger than 36.
If Will be used China's symbols, for example.
As result, I did compress googol in the string '⒁꓃╝ᚙ⬠ꌽ⋊□⇧ꉿ꓄ꁑᔴ┯┃ⵚⵗ—⢺㋜⚡ꐅꅞꎧꈙꇃ⇠︾' and do success decompressing this to bigInt.

**Comment by username1565** [comment]
@P9Q, to do this multilangual, can be expediently using separate files for each language.
But this need to write big arrays for scales in each HTML-file.
Will be better to use more elegand law to do working with prefixes, and suffixes of names for digits.
Then this all can be extend by using LONG SCALE.
I think the code can be writed compactly, if laws will be extracted from OS dll-s or another library.
More operation systems supporting multilangual translating, and this all already exists there.

Also, I did cloning PeterOlson's BigInteger, and modify the main BigInteger.js.
You can see changes here:
https://github.com/username1565/BigInteger/commit/5bfea9f1f2db6dbd2933558dd26ab59e91a2921a

Now I working with UniCode symbols to make convertation BigInteger to Unicode String, and got BigInteger from this string.
This need to contains Unicode Alphabet with copyable symbols, without any special symbols,
and then the base (radix) can be greater and larger than 36.
If Will be used China's symbols, for example.
As result, I did compress googol to 28 symbols, using base 4436 and 4436 unique symbols,
and then I did got successfully decompressing this value to bigInt.
I thins base can be more than 4436, if will be used this all symbols: https://unicode-table.com

**Comment by username1565** [comment]
@P9Q, to do this multilangual, can be expediently using separate files for each language.
But this need to write big arrays for scales in each HTML-file.
Will be better to use more elegand law to do working with prefixes, and suffixes of names for digits.
Then this all can be extend by using LONG SCALE.
I think the code can be writed compactly, if laws will be extracted from OS dll-s or another library.
More operation systems supporting multilangual translating, and this all already exists there.

Also, I did cloning PeterOlson's BigInteger, and modify the main BigInteger.js.
You can see changes here:
https://github.com/username1565/BigInteger/commit/5bfea9f1f2db6dbd2933558dd26ab59e91a2921a

Now I working with UniCode symbols to make convertation BigInteger to Unicode String, and got BigInteger from this string.
This need to contains Unicode Alphabet with copyable symbols, without any special symbols,
and then the base (radix) can be greater and larger than 36.
If Will be used China's symbols, for example.
As result, I did compress googol to 28 symbols, using base 4436 and 4436 unique symbols,
and then I did got successfully decompressing this value to bigInt.
I think base can be more than 4436, if will be used all this symbols: https://unicode-table.com

**Comment by P9Q** [comment]
@username1565 , Nice job go ahead, I hope you create a nice and popular thing 👍
