### ISSUE TITLE
Math.exp() for big int?

### ISSUE THREAD

**Issue by mikemaccana** [peterolson/BigInteger.js#28]
Is there any want to do the equivalent of a `Math.exp()` for bigInt? 

I would try `bigInt(Math.E).pow(2000)` or similar but bigInt obviously only handles ints, not floats.

Thanks for any advice!

**Comment by peterolson** [comment]
A function like `Math.exp` is a real-valued function, not an integer function. What would you expect `bigInt.exp(2000)` to return? Not a `bigInt`, because the result is not an integer, and not a native JavaScript number, because the result is too large to be represented as a native JavaScript number.

To me, this doesn't seem like a function within the scope of an integer library. Do you have any examples of other integer libraries which implement such a thing?

**Comment by mikemaccana** [comment]
Yeah, I got your point from the other issue. Sorry, my original understanding was 'handle big numbers' not `handle things which operate on big numbers`. I've implemented what I needed using `Decimal.exp`. Thanks for your explanations & sorry if I've wasted your time.

**Comment by peterolson** [comment]
No worries :) Thanks for your contributions anyways
