### ISSUE TITLE
Problem with Bitlogic Operations

### ISSUE THREAD

**Issue by Kani1013** [peterolson/BigInteger.js#29]
I am trying to implement the seeded PseudoRandom function from Java to JavaScript.
I've tested the XOR with two bigIntegers:
  "-6931047708307681506" and
  "25214903917"

The result should be
  "-6931047723896018573" but is
  "-6931047723896018575".

after that, I've changed the resulting bigInteger manually to the correct value for further testing.
I am ANDing the correct bigInteger with "281474976710655".
Then the result should be
  "273577603885427" but is
  "7897372825229"

I hope that is enough information for you to reproduce the bug...
Also, I am very certain that this IS a bug, because i've made the same calculations with javascript, java and by hand, and the results from the java- and by-hand calculations were the same.

**Comment by Yaffle** [comment]
```
console.log(bigInt("-1").xor(bigInt("1").toString()); // should be -2 ?
```

**Comment by peterolson** [comment]
The results that are given are what I expected from doing the operation by hand. I suspect this is not a bug, but rather we have different expectations about what the behavior should be. Note that bigInts are not represented using two's complement because there is no bigInt of maximum size. Instead, a sign bit is used.

Here are the bit representations used for the operations you give. The first digit (`1_` or `0_`) is the sign bit, and everything afterwards is the magnitude. The library gives the correct result given this representation.

    1_110000000110000000001110010101100011110111101101111000011100010 // -6931047708307681506
    0_000000000000000000000000000010111011110111011001110011001101101 // 25214903917
    XOR =
    1_110000000110000000001110010111011000000000110100001011010001111 // -6931047723896018575

    1_110000000110000000001110010111011000000000110100001011010001101 // -6931047723896018573
    0_000000000000000111111111111111111111111111111111111111111111111 // 281474976710655
    AND =
    0_000000000000000000001110010111011000000000110100001011010001101 // 7897372825229

1_1 // -1
0_1 // 1
1_0 // -0

**Comment by peterolson** [comment]
The results given are what I expected from doing the operation by hand. I suspect this is not a bug, but rather we have different expectations about what the behavior should be. Note that bigInts are not represented using two's complement because there is no bigInt of maximum size. Instead, a sign bit is used.

Here are the bit representations used for the operations you give. The first digit (`1_` or `0_`) is the sign bit, and everything afterwards is the magnitude. The library gives the correct result given this representation.

    1_110000000110000000001110010101100011110111101101111000011100010 // -6931047708307681506
    0_000000000000000000000000000010111011110111011001110011001101101 // 25214903917
XOR =
    1_110000000110000000001110010111011000000000110100001011010001111 // -6931047723896018575

    1_110000000110000000001110010111011000000000110100001011010001101 // -6931047723896018573
    0_000000000000000111111111111111111111111111111111111111111111111 // 281474976710655
AND =
    0_000000000000000000001110010111011000000000110100001011010001101 // 7897372825229
    
    1_1 // -1
    0_1 // 1
    XOR=
    1_0 // -0

**Comment by peterolson** [comment]
The results given are what I expected from doing the operation by hand. I suspect this is not a bug, but rather we have different expectations about what the behavior should be. Note that bigInts are not represented using two's complement because there is no bigInt of maximum size. Instead, a sign bit is used.

Here are the bit representations used for the operations you give. The first digit (`1_` or `0_`) is the sign bit, and everything afterwards is the magnitude. The library gives the correct result given this representation.

    1_110000000110000000001110010101100011110111101101111000011100010 // -6931047708307681506
    0_000000000000000000000000000010111011110111011001110011001101101 // 25214903917
    XOR =
    1_110000000110000000001110010111011000000000110100001011010001111 // -6931047723896018575

    1_110000000110000000001110010111011000000000110100001011010001101 // -6931047723896018573
    0_000000000000000111111111111111111111111111111111111111111111111 // 281474976710655
    AND =
    0_000000000000000000001110010111011000000000110100001011010001101 // 7897372825229
    
    1_1 // -1
    0_1 // 1
    XOR=
    1_0 // -0

**Comment by Yaffle** [comment]
@peterolson , 
But possibly, people may expect same behaviour as for two's complement integers...

I think, many libs (java.math.BigInteger, ...) provide this behaviour, so if you are not interested in keeping your current behavior, possibly, you might change it.

P.S. I am not using bitwise, so this all is not interesting for me and you can ignore my "voice".

**Comment by peterolson** [comment]
@Yaffle I'm confused about simulating two's complement in big integers. When we have a bounded length, like 4 just as an example, then you can choose `0000 - 0111` to represent from 0 to 7 and `1000-1111` to represent from -8 to -1, but when you numbers can have an arbitrarily long bit length, how do you disambiguate the bit string `1111` between 15 or -1?

That said, since other math libraries seem to somehow deal with this, I'm open to pulling in a commit that matches their behavior.

**Comment by Yaffle** [comment]
possibly, the bit string for negative numbers should be infinity long

**Comment by Kani1013** [comment]
Well I will try to make this work with twos complement.
If I get this to work, I will make a pull request...

**Comment by Kani1013** [comment]
So I got kind of a solution here...
I have implemented the TwosComp BitLogic and in most cases it acts exactly like in Java.
When you exceed 64 bits though, in Java you would get an overflow, but because BigInteger is a library for "arbitrary length integers", my solution just adds another bit and you don't get an overflow. Although this is actually what we want here, it still leads to other results when you get over 64 bits like in my example mentioned in the beginning and thus this doesn't work for my case.

You **can** pass a parameter for the count of bits you want in the ```toTwosComp(bits)``` function, but if this number is too low or not defined, it automatically is made big enough.

_You could pass another parameter, if you explicitly **want** an overflow, which should lead to exactly the same results as in Java, but I **haven't implemented this yet** and I also won't do it, except you want me to._

_Another approach for this problem would be, that if you don't pass a bit count, it automatically picks one big enough, but if you pass one, it will take it, even if you may get an overflow._
**Please give me your feedback on this problem. Thanks!**

I'll make a pull request now, because it works, but If you want me to implement the approach mentioned above, I'll take care of it and you can wait with applying the changes.

**Comment by Kani1013** [comment]
So I now changed the methods behaviour:

If you don't specify a bit count for toTwosCom(), it automatically picks
a big enough number.
If you specify a bit count, it uses it, regardless if you will get an
overflow or not. Therefore you can simulate the same behaviour as in
Java where you have 64 bit but you can also have arbitrary large
numbers.

Same goes for the TwosCom BitLogic functions, where you also might
specify a bit count.

**Comment by peterolson** [comment]
Sorry for the delay on this, I've been waffling back and forth about what should be done. I finally decided to change the bitwise operators to simulate two's complement representation, consistent with Microsoft's System.Numerics.BigInteger and Mathematica. I've decided to implement it myself rather than using the pull request, since I saw a slightly simpler way to implement it.

Let me know if there are any new problems with bitwise operators.
