### ISSUE TITLE
"off by one" issue when comparing toString() and + ''

### ISSUE THREAD

**Issue by thedavidmeister** [peterolson/BigInteger.js#31]
I noticed when using bigInt() that I get different results at some point when comparing math done on bitInt()s that use toString() to calculate the (correct) value and simply adding an empty string (incorrect).

You can see the issue in the console with the data set at https://jsfiddle.net/6nj92xqs/

**Comment by peterolson** [comment]
I know what the problem is, I'm not sure yet if there's a good way to fix it.
There are two object methods that are overriden by bigInts: `toString` and `valueOf`. The `toString` method converts bigInts to a string, and `valueOf` converts them to a JavaScript number. For small numbers, they will have similar results, but if you use sufficiently large numbers, you will notice that there is a difference since they cannot be represented precisely using a 64-bit double:

    bigInt("999999999999999999").toString()
    // "999999999999999999"
    +bigInt("999999999999999999")
    // 1000000000000000000

When an arithmetic operation is performed, including addition, the `valueOf` method is used. Thus, when you do

    bigInt("999999999999999999")+""
    // "1000000000000000000"

it first converts it to a JavaScript number (the `+` operator triggers the `valueOf` method), and then converts that to a string.

When you use a `+` and a string, I can see why you would expect the `toString` to be called rather than the `valueOf`, but as far as I know there's no way to do that. Do you have some solution in mind?

**Comment by thedavidmeister** [comment]
nothing in mind, sorry. I just expected toString() to be called directly rather than in two steps. *Possibly* worth documenting in the README files as something to watch out for if you're new to bigInt() and aren't looking out for subtle language quirks.

**Comment by peterolson** [comment]
OK, I have a note about this in the documentation now.
