### ISSUE TITLE
Feature Request: Desired functionality to read JSON object into bigInt

### ISSUE THREAD

**Issue by UncleSpruce** [peterolson/BigInteger.js#39]
I want to create a constructor for bigInt that can create a bigInt using a json object.

Example:
var jsonBigInt = {"value":[7588586,5407200,7027551,7871450,1855203,3483287,9891367,4339628,2206445,5226736,1375322,864086,9981035,28975],"sign":false,"isSmall":false}
var theBigInt = bigInt(jsonBigInt);
console.log(theBigInt.minus(1).mod(2));

Desired outcome for example code above:
'0' is printed to the console log.

If I have time then I will create this and then commit my changes to the repository.

This library is amazing! Keep up the amazing work.

**Comment by peterolson** [comment]
Hmm, ok, thanks for the suggestion. I need to think about whether or not this is something I want to bake into the library, I'm not sure if this is a very common use case.

Anyway, in the meantime you can do this:

    var theBigInt = new (bigInt("9e16").constructor)(jsonBigInt.value, jsonBigInt.sign);

Note that if the `value` property is small enough, there will most likely be bugs because the implementation assumes that smaller numbers will be represented using a native JavaScript number.

**Comment by peterolson** [comment]
Here's a slightly more robust method:

    var theBigInt = jsonBigInt.isSmall ? bigInt().negate.call(jsonBigInt).negate() : bigInt("9e16").negate.call(jsonBigInt).negate();

Note that the array representation is small endian, that is, the first item is the least significant digit and the last item is the most significant digit, which means that in your case `theBigInt` will be an even number, not an odd number.

I'm closing this issue for now, since I don't see this as a feature that would be used very often. If you come up with a compelling use case, I'll reconsider.
