### ISSUE TITLE
new bigInt(array of bytes) does not work

### ISSUE THREAD

**Issue by limnic** [peterolson/BigInteger.js#44]
In Java, to manipulate a textual string (for example for RSA) you would convert the string to bytes, construct a new BigInteger with the bytes and then do `modPow(...)`. The result would be the encrypted string.

This however does not work with this library. Could this feature be added?

My javascript equivalent test (with BigInteger.min.js version 3bd64ef38bba5e05912922f987f1b16e65798591):
```javascript
var test = "bla";
var bytes = [];

for (var i = 0; i < test.length; i++) {
    bytes.push(test.charCodeAt(i));
}
var bInt = new bigInt(bytes);
console.log(bInt + ", " + bigInt.isInstance(bInt));
bInt.modPow(10, 100);
```
And this yields the following output (Firefox console):
> [object Object], false
> TypeError: bInt.modPow is not a function

Concluding that the constructor failed to create the object.

**Comment by peterolson** [comment]
The problem isn't that `new bigInt(bytes)` isn't working correctly, the problem is that no such constructor exists.

First, `bigInt` is just a function, not a constructor, so using `new` will mess things up. (`new` is used internally for the `BigInteger` and `SmallInteger` classes, but the API doesn't expose those).

Second, `bigInt`s are represented internally using base 10<sup>7</sup>, so I don't feel comfortable providing a method for creating a `bigInt` from an array of bytes, because people might assume that doing so is the cheapest/most low-level way to create a `bigInt`, while it actually would be a fairly expensive operation requiring base conversion.

You can do what you want using a slightly different approach: generate a hex string from the bytes, and then create the `bigInt` using the hex string:

    var test = "bla";
    var hexString = "";

    for (var i = 0; i < test.length; i++) {
        hexString += ("0" + test.charCodeAt(i).toString(16)).slice(-2);
    }

    var bInt = new bigInt(hexString, 16);
    console.log(bInt + ", " + bigInt.isInstance(bInt));
    console.log(+bInt.modPow(10, 100));

Which outputs

> 6450273, true
> 49

Let me know whether that resolves your question.

**Comment by limnic** [comment]
Oh my bad, I assumed it was a
