### ISSUE TITLE
What is .next doing in the docs of notEquals()?

### ISSUE THREAD

**Issue by Numbermaniac** [peterolson/BigInteger.js#63]
https://github.com/peterolson/BigInteger.js#notequalsnumber

Why is there "bigInt(6).next() => 7" in that? That's not related to notEquals...is it?

**Comment by peterolson** [comment]
Good catch, I've corrected the mistake. It looks like it was a copy-and-paste error.

It's slightly embarrassing how long this error has been around. The issue originated in [commit a4f0314  on Sep 9, 2012](https://github.com/peterolson/BigInteger.js/blob/a4f031412d43e257835713ebad526196a0bb0b26/README.md) and slightly evolved in [commit dce746e  on Sep 9, 2012](https://github.com/peterolson/BigInteger.js/blob/dce746ecd3c601f2cd02ee738d60e90c63b8e3f8/README.md) and had been there ever since. Evidently you read the documentation more carefully than anybody else has in the last three years :)
