### ISSUE TITLE
Suddenly, a float?!

### ISSUE THREAD

**Issue by BenWiederhake** [peterolson/BigInteger.js#64]
This may or may not be the right place to report this issue, but I'm in good faith that you can, at least, forward this to the appropriate place. While testing Peter Norvig's [Beal-counterexample-checker](http://norvig.com/bealcheck.html), I observed some bad behavior for certain near-counterexamples like `388288^3 + 18201^4 = 552097^3`:

- The first error message is `A and B have the common factor 6067`. The checker is right about this. I said **near**-counterexample.
- The next message is `A ** x + B ** y is 168285292446216670 and C ** z is 9.290980510367889e+22 but they must be equal.` This is wrong, since [equality *does* hold](https://www.wolframalpha.com/input/?i=388288^3%20%2B%2018201^4%20%3D%20552097^3). This is the reason I'm reporting this issue.

I believe this is a bug in or misuse of the underlying BigInt-implementation, which seems to live in this repository.

Note that this strangely doesn't happen for "more evil" near-counterexamples, e.g. `940463^3 + 31701^4 = 1225772^3`, which only have gcd 10567, which is a prime. But I digress :)

**Comment by peterolson** [comment]
Peter Norvig wrote something (admittedly a small toy program) using this library? I feel so flattered.

I haven't investigated the issue yet, I'll look into it in the next few days.

**Comment by Yaffle** [comment]
@BenWiederhake , seems, you was calculating `552097^4` which is `92909805103678886513281`,  
`" and C ** z is " + C.pow(z)` is evaulated as `" and C ** z is " + C.pow(z).valueOf().toString()`
and so you see `9.290980510367889e+22`
Please check.

**Comment by peterolson** [comment]
@Yaffle is correct. It appears that you accidentally entered `552097 ** 4` instead of `552097 ** 3`, which seems to have the expected behavior.

The issue about the string representation is the same as in issue #31. There's a subtle language quirk involved here where `"string" + bigInt` will call the `valueOf` function on the big integer first instead of the `toString` function. I'm considering removing the `valueOf` override for this reason, since concatenating big integers with strings might be more commonly desired than converting them to Javascript numbers implicitly, but I'm a little hesitant since this would be a breaking change.

**Comment by BenWiederhake** [comment]
Sounds reasonable. So it all was just a typo on my end. Aww :(
