### ISSUE TITLE
most strange behaviour running ```bigInt(12345).pow(4).pow(1/4)```

### ISSUE THREAD

**Issue by davidedc** [peterolson/BigInteger.js#74]
```bigInt(12345).pow(3).pow(1/3)``` works fine (or, better, ```bigInt(12345).pow(3).pow(1/3 + 0.0000001)``` does, see previous issue).

But running ```bigInt(12345).pow(4).pow(1/4)``` from the console makes Chrome incapable or answering any other command:

<img width="416" alt="screen shot 2016-04-01 at 16 40 32" src="https://cloud.githubusercontent.com/assets/769568/14211939/8044bd8e-f828-11e5-995c-da5f87810a06.png">

the console appears responsive but no answers come for it... May be a browser problem...

**Comment by peterolson** [comment]
The `pow` method does not support fractions. The fact that `bigInt(12345).pow(3).pow(1/3 + 0.0000001)` seems to work correctly is pure luck; there is no code designed support the cube root operation (or any other root).

In any case, these inputs should probably cause an error to be thrown, instead of silently failing with an infinite loop or garbage output.

**Comment by davidedc** [comment]
( for whoever ends up here needing roots of bigInts, see https://github.com/peterolson/BigInteger.js/issues/73 )

**Comment by peterolson** [comment]
I've pushed a change that causes this to throw an error instead of failing silently.

**Comment by brandonros** [comment]
what is the proper way to do cube root with this library?
